backend = "glx";
glx-copy-from-front = false;

use-damage = false;
vsync = true;

 corner-radius = 7

inactive-opacity = .75
active-opacity = .75
frame-opacity = .75
inactive-opacity-override = false

# Blur 
blur-method = "dual_kawase"
blur-strength = 3
blur-background = true
blur-background-frame = false
blur-background-fixed = false

fading = true
fade-delta = 4
fade-in-step = 0.05
fade-out-step = 0.05

unredir-if-possible = false; # Prevents Picom from turning off during rapid changes
shadow = true
shadow-radius =.8
shadow-offset-x = 0
shadow-offset-y = 0
shadow-opacity = 0.7
cursor-shadow = false

# Window types
wintypes:
{
    tooltip = { fade = true; shadow = true; opacity = 0.755; focus = true; blur = false; };
    dock = { opacity = 1.0; shadow = false; blur = false; };
    desktop = { opacity = 1.0; shadow = false; blur = false; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 1.0; shadow = false; };
    dropdown_menu = { opacity = 1.0; shadow = false; };
}

#exclusions
#
shadow-exclude = [
    "window_type = 'desktop'",
    "class_g = 'conky'",
    "class_g = 'steam_app_230410'",
    "class_g = 'i3lock'",
    "class_g = 'Minecraft* 26.1.1'",
    "class_g = 'Minecraft* 26.2'",
    "class_g = 'Gimp'",
    "class_g = 'steam_app_1240440'",
    "class_g = 'steam_app_782330'",
    "class_g = 'Picture-in-Picture'",
    "class_g = 'starcitizen.exe'"
];

blur-background-exclude = [
    "window_type = 'desktop'",
    "class_g = 'conky'",
    "class_g = 'steam_app_230410'",
    "class_g = 'Minecraft* 26.1.1'",
    "class_g = 'Minecraft* 26.1.2'",
    "class_g = 'Minecraft* 26.2'",
    "class_g = 'steam_app_782330'",
    "class_g = 'Gimp'",
    "class_g = 'steam_app_1240440'",
    "class_g = 'Picture-in-Picture'",
    "class_g = 'i3lock'",
    "class_g = 'starcitizen.exe'"

];

window-rule = {
    match = [
        "class_g = 'conky'",
        "class_g ~ '(?i)^steam'",
        "class_g ~ 'Minecraft* 26.1.1'",
	"class_g = 'Minecraft* 26.2'",
	"class_g = 'Minecraft* 26.1.2'",
	"class_g = 'steam_app_782330'",
	"class_g = 'Gimp'",
	"class_g = 'steam_app_1240440'",
	"class_g = 'Picture-in-Picture'",
	"class_g = 'i3lock'",
    "class_g = 'starcitizen.exe'"

    ];
    opacity = 1.0;
    blur = false;
    shadow = false;
    corner-radius = 0;
};

opacity-rule = [
    "100:class_g = 'steam_app_230410'",
    "100:class_g = 'Minecraft* 26.1.1'",
    "100:class_g = 'Minecraft* 26.1.2'",
    "100:class_g = 'steam_app_1240440'",
    "100:class_g = 'Gimp'",
    "100:class_g = 'steam_app_782330'",
    "100:class_g = 'i3lock'",
    "100:class_g = 'Picture-in-Picture'",
    "100:class_g = 'starcitizen.exe'",
    "100:class_g = 'Minecraft* 26.2'"

];
