enable_audio_bell no
font_size 12
font_family JetBrainsMono Nerd Font
map alt+shift+h previous_tab
map alt+shift+j scroll_line_down
map alt+shift+k scroll_line_up
map alt+shift+l next_tab
map alt+shift+n new_tab
map alt+shift+w close_window
map alt+ctrl+k next_window
map alt+ctrl+j previous_window

map shift+alt+t set_tab_title


map alt+j goto_tab 1
map alt+k goto_tab 2
map alt+l goto_tab 3
