 conky.config = {

alignment = 'top_right',

gap_x = -2550,

gap_y = 0,

own_window = true,

own_window_type = 'normal',

own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

own_window_transparent = true,

own_window_argb_visual = true,

own_window_argb_value = 0, -- fully transparent

double_buffer = true,

update_interval = .1,

minimum_width = 260,

maximum_width = 490,

minimum_height = 1440,

maximum_height = 2560,

use_xft = true,

font = 'Ubuntu Sans Mono Medium Italic:size=12',

default_color = '#00c161',

};

conky.text = [[
${voffset 10}
${font} Scarlet Citadel ${exec "grep PRETTY_NAME /etc/os-release | cut -d'"' -f2"}
${hr 2}
${font} WORKSPACE
${exec wmctrl -d | awk '/\*/ {print $NF}'}
${hr 2}
${execpi 5 bash -c '
cores=$(nproc)
for ((i=1;i<=cores;i++)); do
echo "Core $i \${color}\${cpubar cpu$i 8}\${color}"
done
'}
${hr 1}
cpu temp is ${execi 2 cat /sys/class/hwmon/hwmon2/temp1_input | awk '{printf "%.1f°C", $1/1000}'}
${hr 1}
${font} SSD
${hr 2}
${fs_used} / ${fs_size} ${fs_bar 10, 100/}
${hr 2}
${font} MEMORY
${hr 2}
RAM ${alignr}${memperc}%
${membar 8}
${color} ${mem /} / ${memmax}
SWAP ${alignr}${swapperc}%
${color} ${swap /} / ${swapmax} ${swapbar 10}
${font} PING
${hr 2}
${execi 5 bash -c "ping -c1 -W1 1.1.1.1 | grep time= | sed 's/.*time=//;s/ ms//'"} ms
${font} VPN (Mullvad)
${if_existing /sys/class/net/wg0-mullvad}
${color green}Connected${color}
location: ${exec curl https://am.i.mullvad.net/city}
Down ${alignr}${downspeedf wg0-mullvad} KB/s
Up   ${alignr}${upspeedf wg0-mullvad} KB/s
${else}
${color red}Disconnected${color}
${endif}

]]
