[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #FF0000
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/left]
monitor = DP-0
width = 100%
height = 30pt
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 2

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font

modules-left = xworkspaces rofi date song
modules-center = world-clock
modules-right = xwindow timer pulseaudio memory cpu cpu_temp Mullvad-city powerbutton  


cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

 wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true


[bar/right]
monitor = DP-4
width = 100%
height = 30pt
;radius = 6

font-0 = JetBrainsMono Nerd Font

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 2

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}


modules-left = xworkspaces rofi date song
modules-center = world-clock
modules-right = xwindow timer pulseaudio memory cpu cpu_temp Mullvad-city powerbutton

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
 wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%


[module/rofi]
type=custom/text
label = ""
click-left = rofi -show drun 



[module/filesystem]
type = internal/fs
interval = 25

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = 󰖁
label-muted-foreground = ${colors.disabled}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/world-clock]
type = custom/script
exec = /home/crimson/.config/polybar/time.sh
interval = 1
format = <label>
label = %output%
label-padding = 1
click-left = /home/crimson/.config/polybar/worldclock.sh 

[module/powerbutton]
type = custom/text 
label-font = 0
label = ""
click-left = /home/crimson/.config/i3/power.sh

[module/calendar]
type = internal/date
exec = /home/crimson/.date.sh
intervel = 1
click-left = /home/crimson/calender.sh
label = %output%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected


[module/Mullvad-city]
type = custom/script
exec = curl -s https://am.i.mullvad.net/city

[module/song]
type=custom/script
exec=~/.config/polybar/song.sh
interval=2
format=<label>
format-prefix=" "
click-left=playerctl play-pause
label=%output:0:65:...%



[module/timer]
type = custom/script
exec = ~/.config/polybar/timer-bar.sh
interval = 1
click-left=~/.config/polybar/timer-controls.sh
tooltip = 1


[module/timer-space]
type = custom/text
content = " "
click-left=~/.config/polybar/timer-controls.sh &



[module/OS]
type=custom/script
exec =  grep PRETTY_NAME /etc/os-release | cut -d'"' -f2
interval = 120

[module/cpu_temp]
type = internal/temperature
interval = 1
thermal-zone = 0
hwmon-path = /sys/class/hwmon/hwmon2/temp1_input

[module/date]
type = internal/date
interval = 1

date = %m/%d %a

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
